### ISSUE TITLE
Allowing extra trailing text, aka partial matches/anchoring

### ISSUE THREAD

**Issue by IndianBoy42** [mathematic-inc/unfmt#23]
For example in `unformat!("Hello world {:usize}", "Hello world 64 something")` it should find the match and get `64` as the return value

**Comment by jrandolf-old** [comment]
Partial match is possible as long as the last capture is delimited. For example, `Hello world {:usize} ` (note the space at the end) instead of `Hello world {:usize}`. Think of captures as `(.*?)` in regular expressions.
