### ISSUE TITLE
The return type is inconsistent in case of a singular capture

### ISSUE THREAD

**Issue by magistau** [mathematic-inc/unfmt#79]
- `unformat!("foo", input)` returns an `Option<()>`
- `unformat!("foo{:u8}bar")` returns an `Option<u8>`
- `unformat!("foo{:u8}bar{:u8}baz")` returns an `Option<(u8, u8)>`
- `unformat!("foo{:u8}bar{:u8}baz{:u8}qux")` returns an `Option<(u8, u8, u8)>`
- `unformat!("foo{:u8}bar{:u8}baz{:u8}qux{:u8}quux")` returns an `Option<(u8, u8, u8, u8)>`

IMHO the second one should return `Option<(u8,)>` for consistency instead

**Comment by jrandolf-old** [comment]
We used to return `Option<(u8,)>`, but we found in production it's simpler to just return the type directly.
